server:
  port: 18001

eureka:
  instance:
    hostname: std-eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
      #启用主动失效，并且每次主动失效检测间隔为3s
      eviction-interval-timer-in-ms: 3000
      #eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
      #默认30s
      responseCacheUpdateInvervalMs: 1000
      # 关闭自我保护模式（缺省为打开）
      enable-self-preservation: false
