server:
  port: 19011

# spring.application.name必须要设置，服务消费者将通过该名称调用所提供的服务。
spring:
  application:
    name: eureka-client-consumer

# eureka.client.service-url也必须设置，表示我们要向那些Eureka服务器进行服务注册，这里可以声明多个Eureka服务器
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18001/eureka
