spring:
  datasource:
    ####### druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: '{cipher}149bd75747e51228e9d0b945b70df4c7aa10cb2018008e88068179add8aba2a144db9e9660d748bbfbdcf2118f63af0687100cb3ab996863d912dd7871e61458b04342ed3165663a74f6c3a30229aad5123aee973b4c64ec6248cf9a4a2b4a6e'
    username: '{cipher}257efd9bdb500853efebf3a83cc5ceeb5b0f82d818d6671e0af7058c9c9949eb'
    password: '{cipher}410c910d99d527c47f3deaa3ed1046922ff02340ba39f3b834d083205ecb1db2'
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
##########################################
  jpa:
    database: MYSQL
    show-sql: true
# 第一次创建表,后期更改实体不更新表
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  freemarker:
    charset:  UTF-8