spring:
    mail:
       host: smtp.ym.163.com
       username:  service@zuhr.me
       password: '{cipher}68cc6337acc3e95d2eb6abcef0cbddff9900e4c8cc3330e71ab7e13acc5ae3e0'
       properties:
          mail:
            smtp:
              #这样才能通过验证
              auth: true
              starttls:
                  enable: true
                  required: true
